### ISSUE TITLE
EC can change vault parameters and update UI via Econ Gov UI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#32]
**Is your feature request related to a problem? Please describe.**

Vaults will be predominantly governed by the EC. There are several contract functions and parameters that they will need to manage. As part of efforts to decentralize dapp hosting, they will also need to update Vaults UI by publishing content hashes when appropriate.

The scope of this ticket will be for parameters changes and updating Vault UI within the Econ Gov UI.

**Describe the solution you'd like**

The EC controls for the following vault manager parameters:

- [x] Interest Rate (%)

  - Select Vault Manager -> Show current IR -> Allow % input change -> Propose

- [x] vault creation fee (%) (aka loanFee)

  - Select Vault Manager -> Show current vault creation fee -> Allow $ input change -> Propose

- [ ] minimum initial debt ($)

  - Select Vault Manager -> Show current minimum initial debt ($) -> Allow $ input change -> Propose

- [x] liquidation ratio (%) (aka LiquidationMargin)

  - Select Vault Manager -> Show current liquidation ratio (%) -> Allow % input change -> Propose

- [x] mint limit ($) (aka debtLimit)

  - Select Vault Manager -> Show current mint limit -> Allow $ input change -> Propose

- [x] minimum collateralization ratio (MCR) (%)

  - Select Vault Manager -> Show current minimum collateralization ratio (%) -> Allow % input change -> Propose

- [ ] Liquidation Penalty (%)

  - Select Vault Manager -> Show current liquidation penalty (%) -> Allow % input change -> Propose 

- [ ] Publish updated Vault UI
-field where EC member can paste more recent hash. Once vote passes it's published to the Agoric chain where it can be queried. Dependent on https://github.com/Agoric/agoric-sdk/issues/6860 and https://github.com/Agoric/agoric-sdk/issues/4350
